[project]
name = "tinyflow"
version = "0.1.0"
description = "A short and sweet implementation of generative flow models."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beartype>=0.22.4",
    "datasets>=4.8.5",
    "diffrax>=0.7.2",
    "drawsvg>=2.4.1",
    "einops>=0.8.1",
    "fidax>=0.3.1",
    "equinox>=0.13.2",
    "grain>=0.2.14",
    "jax[cuda13]>=0.8.0",
    "jaxtyping>=0.3.3",
    "numpy>=2.4.4",
    "optax>=0.2.6",
    "pillow>=12.2.0",
    "tqdm>=4.67.3",
    "typer-slim>=0.20.0",
    "matplotlib>=3.11.2",
]

[tool.setuptools.packages.find]
include = ["data*", "models*"]

[tool.ruff.lint]
extend-select = [
    "N",        # Enforce naming convention
    "A",        # Detect shadowed builtins
    "D",        # Documentation
    "F",        # Pyflakes rules
    "W",        # PyCodeStyle warnings
    "E",        # PyCodeStyle errors
    "I",        # Sort imports properly
    "UP",       # Warn if certain things can changed due to newer Python versions
    "C4",       # Catch incorrect use of comprehensions, dict, list, etc
    "FA",       # Enforce from __future__ import annotations
    "ISC",      # Good use of string concatenation
    "ICN",      # Use common import conventions
    "RET",      # Good return practices
    "SIM",      # Common simplification rules
    "TID",      # Some good import practices
    "TC",       # Enforce importing certain types in a TYPE_CHECKING block
    "PTH",      # Use pathlib instead of os.path
    "TD",       # Be diligent with TODO comments
    "NPY",      # Some numpy-specific things
]
ignore = ['F722']

[tool.ruff.lint.pydocstyle]
convention = "google"

[dependency-groups]
dev = [
    "scikit-learn>=1.9.1",
]
